---
- name: create couchdb-lucene-data
  become: yes
  become: '{{docker_couchdb_user}}'
  docker:
    name: couchdb-lucene-data
    image: '{{docker_couchdb_lucene_container}}'
    state: present
    volumes:
      - /opt/couchdb-lucene/indexes
      - /opt/couchdb-lucene/logs
    
- name: launch couchdb-lucene
  become: yes
  become: '{{docker_couchdb_user}}'
  docker:
    name: couchdb-lucene
    hostname: couchdb-lucene
    image: '{{docker_couchdb_lucene_container}}'
    state: started
    restart_policy: always
    ports:
      - "{{docker_couchdb_lucene_host_port}}:5985"
    volumes_from:
      - couchdb-lucene-data
    extra_hosts:
      couch-tunnel: '{{ hostvars[inventory_hostname]["ansible_default_ipv4"]["address"] }}'

- name: create couchdb-data
  become: yes
  become: '{{docker_couchdb_user}}'
  docker:
    name: couchdb-data
    image: '{{docker_couchdb_container}}'
    state: present
    volumes:
      - /usr/local/var/lib/couchdb
      - /usr/local/var/log/couchdb
    
- name: launch couchdb
  become: yes
  become: '{{docker_couchdb_user}}'
  docker:
    name: couchdb
    hostname: couchdb
    image: '{{docker_couchdb_container}}'
    restart_policy: always
    state: started
    links:
      - "couchdb-lucene:couchdb-lucene"
    ports:
      - "{{docker_couchdb_host_port}}:5984"
    volumes_from:
      - couchdb-data
    extra_hosts:
      couch-tunnel: '{{ hostvars[inventory_hostname]["ansible_default_ipv4"]["address"] }}'
